%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MATLAB Code Generated with Fuzzy Logic Designer App                     %
%                                                                         %
% Date: 09-Mar-2025 13:22:39                                              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Fuzzy Inference System 1
% Construct FIS
NatureBasedRiskFis = mamfis(Name="NatureBasedRiskFis");
% Input 1
NatureBasedRiskFis = addInput(NatureBasedRiskFis,[0 50],Name="Temperature");
NatureBasedRiskFis = addMF(NatureBasedRiskFis,"Temperature","trimf",[0 0 18], ...
    Name="Low",VariableType="input");
NatureBasedRiskFis = addMF(NatureBasedRiskFis,"Temperature","trimf",[15 22.5 28], ...
    Name="Medium",VariableType="input");
NatureBasedRiskFis = addMF(NatureBasedRiskFis,"Temperature","trimf",[25 35 50], ...
    Name="High",VariableType="input");
% Input 2
NatureBasedRiskFis = addInput(NatureBasedRiskFis,[0 100],Name="Humidity");
NatureBasedRiskFis = addMF(NatureBasedRiskFis,"Humidity","trimf",[0 22.5 45], ...
    Name="Low",VariableType="input");
NatureBasedRiskFis = addMF(NatureBasedRiskFis,"Humidity","trimf",[40 50 60], ...
    Name="Medium",VariableType="input");
NatureBasedRiskFis = addMF(NatureBasedRiskFis,"Humidity","trimf",[55 77.5 100], ...
    Name="High",VariableType="input");
% Input 3
NatureBasedRiskFis = addInput(NatureBasedRiskFis,[0 100],Name="EarthquakeProbability");
NatureBasedRiskFis = addMF(NatureBasedRiskFis,"EarthquakeProbability","trimf",[0 0 20], ...
    Name="Low",VariableType="input");
NatureBasedRiskFis = addMF(NatureBasedRiskFis,"EarthquakeProbability","trimf",[20 35 50], ...
    Name="Medium",VariableType="input");
NatureBasedRiskFis = addMF(NatureBasedRiskFis,"EarthquakeProbability","trimf",[50 75 100], ...
    Name="High",VariableType="input");
% Output 1
NatureBasedRiskFis = addOutput(NatureBasedRiskFis,[0 10],Name="NatureRisk");
NatureBasedRiskFis = addMF(NatureBasedRiskFis,"NatureRisk","trimf",[-4.16667 0 4.16667], ...
    Name="Low",VariableType="output");
NatureBasedRiskFis = addMF(NatureBasedRiskFis,"NatureRisk","trimf",[0.833333 5 9.16667], ...
    Name="Medium",VariableType="output");
NatureBasedRiskFis = addMF(NatureBasedRiskFis,"NatureRisk","trimf",[5.83333 10 14.1667], ...
    Name="High",VariableType="output");
% Rules
NatureBasedRiskFis = addRule(NatureBasedRiskFis,[3 3 3 3 1 1; ...
    3 3 0 3 1 1; ...
    0 0 3 3 1 1; ...
    3 0 3 3 1 1; ...
    2 2 2 2 1 1; ...
    3 2 0 2 1 1; ...
    3 0 2 2 1 1; ...
    2 0 3 2 1 1; ...
    1 1 1 1 1 1; ...
    1 0 0 1 1 1; ...
    0 1 0 1 1 1; ...
    0 0 1 1 1 1]);

%% Fuzzy Inference System 2
% Construct FIS
HumanBasedRiskFis = mamfis(Name="HumanBasedRiskFis");
% Input 1
HumanBasedRiskFis = addInput(HumanBasedRiskFis,[0 10],Name="OperatorErrorRate");
HumanBasedRiskFis = addMF(HumanBasedRiskFis,"OperatorErrorRate","trimf",[-4.16667 0 4.16667], ...
    Name="Low",VariableType="input");
HumanBasedRiskFis = addMF(HumanBasedRiskFis,"OperatorErrorRate","trimf",[0.833333 5 9.16667], ...
    Name="Medium",VariableType="input");
HumanBasedRiskFis = addMF(HumanBasedRiskFis,"OperatorErrorRate","trimf",[5.83333 10 14.1667], ...
    Name="High",VariableType="input");
% Input 2
HumanBasedRiskFis = addInput(HumanBasedRiskFis,[0 10],Name="MaintenanceQuality");
HumanBasedRiskFis = addMF(HumanBasedRiskFis,"MaintenanceQuality","trimf",[-4.16667 0 4.16667], ...
    Name="Low",VariableType="input");
HumanBasedRiskFis = addMF(HumanBasedRiskFis,"MaintenanceQuality","trimf",[0.833333 5 9.16667], ...
    Name="Medium",VariableType="input");
HumanBasedRiskFis = addMF(HumanBasedRiskFis,"MaintenanceQuality","trimf",[5.83333 10 14.1667], ...
    Name="High",VariableType="input");
% Output 1
HumanBasedRiskFis = addOutput(HumanBasedRiskFis,[0 10],Name="HumanRisk");
HumanBasedRiskFis = addMF(HumanBasedRiskFis,"HumanRisk","trimf",[-4.16667 0 4.16667], ...
    Name="Low",VariableType="output");
HumanBasedRiskFis = addMF(HumanBasedRiskFis,"HumanRisk","trimf",[0.833333 5 9.16667], ...
    Name="Medium",VariableType="output");
HumanBasedRiskFis = addMF(HumanBasedRiskFis,"HumanRisk","trimf",[5.83333 10 14.1667], ...
    Name="High",VariableType="output");
% Rules
HumanBasedRiskFis = addRule(HumanBasedRiskFis,[3 1 3 1 1; ...
    3 0 3 1 1; ...
    0 1 3 1 1; ...
    2 2 2 1 1; ...
    3 2 2 1 1; ...
    2 1 2 1 1; ...
    1 3 1 1 1; ...
    1 0 1 1 1; ...
    0 3 3 1 1]);

%% Fuzzy Inference System 3
% Construct FIS
HardwareBasedRisk = mamfis(Name="HardwareBasedRisk");
% Input 1
HardwareBasedRisk = addInput(HardwareBasedRisk,[0 20],Name="ServerAge");
HardwareBasedRisk = addMF(HardwareBasedRisk,"ServerAge","trimf",[0 0 6], ...
    Name="Low",VariableType="input");
HardwareBasedRisk = addMF(HardwareBasedRisk,"ServerAge","trimf",[4 10 12], ...
    Name="Medium",VariableType="input");
HardwareBasedRisk = addMF(HardwareBasedRisk,"ServerAge","trimf",[10 20 20], ...
    Name="High",VariableType="input");
% Input 2
HardwareBasedRisk = addInput(HardwareBasedRisk,[0 100],Name="SystemLoad");
HardwareBasedRisk = addMF(HardwareBasedRisk,"SystemLoad","trimf",[0 0 30], ...
    Name="Low",VariableType="input");
HardwareBasedRisk = addMF(HardwareBasedRisk,"SystemLoad","trimf",[20 50 80], ...
    Name="Medium",VariableType="input");
HardwareBasedRisk = addMF(HardwareBasedRisk,"SystemLoad","trimf",[70 100 100], ...
    Name="High",VariableType="input");
% Input 3
HardwareBasedRisk = addInput(HardwareBasedRisk,[0 10],Name="PowerSupplyStability");
HardwareBasedRisk = addMF(HardwareBasedRisk,"PowerSupplyStability","trimf",[0 1.5 3], ...
    Name="Low",VariableType="input");
HardwareBasedRisk = addMF(HardwareBasedRisk,"PowerSupplyStability","trimf",[2 5 8], ...
    Name="Medium",VariableType="input");
HardwareBasedRisk = addMF(HardwareBasedRisk,"PowerSupplyStability","trimf",[7 8.5 10], ...
    Name="High",VariableType="input");
% Output 1
HardwareBasedRisk = addOutput(HardwareBasedRisk,[0 10],Name="HardwareRisk");
HardwareBasedRisk = addMF(HardwareBasedRisk,"HardwareRisk","trimf",[-4.16667 0 4.16667], ...
    Name="Low",VariableType="output");
HardwareBasedRisk = addMF(HardwareBasedRisk,"HardwareRisk","trimf",[0.833333 5 9.16667], ...
    Name="Medium",VariableType="output");
HardwareBasedRisk = addMF(HardwareBasedRisk,"HardwareRisk","trimf",[5.83333 10 14.1667], ...
    Name="High",VariableType="output");
% Rules
HardwareBasedRisk = addRule(HardwareBasedRisk,[3 3 1 3 1 1; ...
    3 3 0 3 1 1; ...
    0 3 1 3 1 1; ...
    3 0 1 3 1 1; ...
    2 2 2 2 1 1; ...
    3 2 0 2 1 1; ...
    0 3 2 2 1 1; ...
    2 0 1 2 1 1; ...
    1 1 3 1 1 1; ...
    1 0 0 1 1 1; ...
    0 1 0 1 1 1; ...
    0 0 3 1 1 1]);

%% Fuzzy Inference System 4
% Construct FIS
OverallServerFailureRisk = mamfis(Name="OverallServerFailureRisk");
% Input 1
OverallServerFailureRisk = addInput(OverallServerFailureRisk,[0 10],Name="NatureBasedRiskFis");
OverallServerFailureRisk = addMF(OverallServerFailureRisk,"NatureBasedRiskFis","trimf",[-4.16667 0 4.16667], ...
    Name="Low",VariableType="input");
OverallServerFailureRisk = addMF(OverallServerFailureRisk,"NatureBasedRiskFis","trimf",[0.833333 5 9.16667], ...
    Name="Medium",VariableType="input");
OverallServerFailureRisk = addMF(OverallServerFailureRisk,"NatureBasedRiskFis","trimf",[5.83333 10 14.1667], ...
    Name="High",VariableType="input");
% Input 2
OverallServerFailureRisk = addInput(OverallServerFailureRisk,[0 10],Name="HumanBasedRiskFis");
OverallServerFailureRisk = addMF(OverallServerFailureRisk,"HumanBasedRiskFis","trimf",[-4.16667 0 4.16667], ...
    Name="Low",VariableType="input");
OverallServerFailureRisk = addMF(OverallServerFailureRisk,"HumanBasedRiskFis","trimf",[0.833333 5 9.16667], ...
    Name="Medium",VariableType="input");
OverallServerFailureRisk = addMF(OverallServerFailureRisk,"HumanBasedRiskFis","trimf",[5.83333 10 14.1667], ...
    Name="High",VariableType="input");
% Input 3
OverallServerFailureRisk = addInput(OverallServerFailureRisk,[0 10],Name="HardwareBasedRiskFis");
OverallServerFailureRisk = addMF(OverallServerFailureRisk,"HardwareBasedRiskFis","trimf",[-4.16667 0 4.16667], ...
    Name="Low",VariableType="input");
OverallServerFailureRisk = addMF(OverallServerFailureRisk,"HardwareBasedRiskFis","trimf",[0.833333 5 9.16667], ...
    Name="Medium",VariableType="input");
OverallServerFailureRisk = addMF(OverallServerFailureRisk,"HardwareBasedRiskFis","trimf",[5.83333 10 14.1667], ...
    Name="High",VariableType="input");
% Output 1
OverallServerFailureRisk = addOutput(OverallServerFailureRisk,[0 100],Name="OverallFailureRisk");
OverallServerFailureRisk = addMF(OverallServerFailureRisk,"OverallFailureRisk","trimf",[-41.6667 0 41.6667], ...
    Name="Low",VariableType="output");
OverallServerFailureRisk = addMF(OverallServerFailureRisk,"OverallFailureRisk","trimf",[8.33333 50 91.6667], ...
    Name="Medium",VariableType="output");
OverallServerFailureRisk = addMF(OverallServerFailureRisk,"OverallFailureRisk","trimf",[58.3333 100 141.667], ...
    Name="High",VariableType="output");
% Rules
OverallServerFailureRisk = addRule(OverallServerFailureRisk,[3 3 3 3 1 1; ...
    3 3 0 3 1 1; ...
    0 3 3 3 1 1; ...
    3 0 3 3 1 1; ...
    2 2 2 2 1 1; ...
    3 2 0 2 1 1; ...
    0 3 2 2 1 1; ...
    2 0 3 2 1 1; ...
    1 1 1 1 1 1; ...
    1 0 0 1 1 1; ...
    0 1 0 1 1 1; ...
    0 0 1 1 1 1]);
fuzzySystems = [NatureBasedRiskFis HumanBasedRiskFis HardwareBasedRisk OverallServerFailureRisk];

%% FIS Tree Connections
connections = [ ...
    "NatureBasedRiskFis/NatureRisk" "OverallServerFailureRisk/NatureBasedRiskFis"; ...
    "HumanBasedRiskFis/HumanRisk" "OverallServerFailureRisk/HumanBasedRiskFis"; ...
    "HardwareBasedRisk/HardwareRisk" "OverallServerFailureRisk/HardwareBasedRiskFis" ...
    ];

%% Construct FIS Tree
ServerFailureModel = fistree(fuzzySystems,connections, ...
    Name="ServerFailureModel");

%% Update FIS Tree Outputs
ServerFailureModel.Outputs = ["NatureBasedRiskFis/NatureRisk", ...
    "HumanBasedRiskFis/HumanRisk", ...
    "HardwareBasedRisk/HardwareRisk", ...
    "OverallServerFailureRisk/OverallFailureRisk"];